name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build dist artifacts
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          mkdir -p dist
          COMMIT=$(git rev-parse --short HEAD || echo none)
          DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          build() {
            os=$1; arch=$2
            name="veessh_${VERSION}_${os}_${arch}"
            outdir="dist/${name}"
            mkdir -p "$outdir"
            ldflags="-s -w -X github.com/alex-vee-sh/veessh/internal/version.Version=${VERSION} -X github.com/alex-vee-sh/veessh/internal/version.Commit=${COMMIT} -X github.com/alex-vee-sh/veessh/internal/version.Date=${DATE}"
            GOOS=$os GOARCH=$arch CGO_ENABLED=0 \
              go build -trimpath -ldflags "$ldflags" -o "$outdir/veessh" ./cmd/veessh
            tar -C dist -czf "dist/${name}.tar.gz" "$name"
            sha256sum "dist/${name}.tar.gz" > "dist/${name}.tar.gz.sha256"
            rm -rf "$outdir"
          }
          build darwin amd64
          build darwin arm64
          build linux amd64
          build linux arm64
          ls -lah dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: veessh ${{ github.ref_name }}
          body: |
            First automated release.
          draft: false
          prerelease: false
          files: |
            dist/veessh_${{ github.ref_name }}_darwin_amd64.tar.gz
            dist/veessh_${{ github.ref_name }}_darwin_amd64.tar.gz.sha256
            dist/veessh_${{ github.ref_name }}_darwin_arm64.tar.gz
            dist/veessh_${{ github.ref_name }}_darwin_arm64.tar.gz.sha256
            dist/veessh_${{ github.ref_name }}_linux_amd64.tar.gz
            dist/veessh_${{ github.ref_name }}_linux_amd64.tar.gz.sha256
            dist/veessh_${{ github.ref_name }}_linux_arm64.tar.gz
            dist/veessh_${{ github.ref_name }}_linux_arm64.tar.gz.sha256
